---
title: "Analysis-Defense"
author: "Tom Offrede"
date: "2024-04-26"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lmerTest)
library(ggdist)
library(broom.mixed)

`%!in%` <- Negate(`%in%`)

folder <- "C:/Users/offredet/Documents/1HU/ExperimentEyes/Data/All/"
folderConvPlots <- "C:/Users/offredet/Documents/1HU/ExperimentEyes/Defense/"
files <- list.files(folder, "RData")
fileBase <- files[grepl("Baseline", files)]
fileConv <- files[grepl("Conversation", files) & !grepl("Including", files)]

load(paste0(folder, "dataBaseline.RData"))
load(paste0(folder, "dataConversation.RData"))

dac <- dac[!grepl("Impairment|Dyslexia|Gender|Education|Age", names(dac))]

dac <- dac %>%
  filter(!grepl("Robot", speaker)) %>% 
  mutate_at(c("turnDur", "turn", "f0mean", "f0sd", "intensMean", "intensMax", "robPrevf0mean", "robPrevf0meanMock", "gapDur", "intimMean", "intimSD", "intimMed", "IPUDur", "robPrevf0sd", "robPrevf0sdMock", "robPrevIntMean", "robPrevIntMeanMock", "robPrevIntMax", "robPrevIntMaxMock"), as.numeric) %>%
  mutate_at(c("speaker", "condition", "Order", "task"), as.factor) %>% 
  group_by(speaker) %>%
  mutate(turnDurNormal = (turnDur - min(turnDur, na.rm = TRUE)) / (max(turnDur, na.rm = TRUE) - min(turnDur, na.rm = TRUE)),
         turnDurc = turnDur - mean(turnDur, na.rm=TRUE),
         robf0meanc = robPrevf0mean - mean(robPrevf0mean, na.rm=TRUE),
         robf0sdc = robPrevf0sd - mean(robPrevf0sd, na.rm=TRUE),
         robIntMeanc = robPrevIntMean - mean(robPrevIntMean, na.rm=TRUE),
         robIntMaxc = robPrevIntMax - mean(robPrevIntMax, na.rm=TRUE),
         intimc = intimMean - mean(intimMean, na.rm=TRUE),
         intensMeanC = intensMean - mean(intensMean, na.rm=TRUE),
         intensMaxC = intensMax - mean(intensMax, na.rm=TRUE),
         f0CV = f0sd / f0mean,
         robf0CV = robPrevf0sd / robPrevf0mean,
         robf0CVc = robf0CV - mean(robf0CV, na.rm=TRUE),
         mockf0meanC = robPrevf0meanMock - mean(robPrevf0meanMock, na.rm=TRUE),
         mockf0sdC = robPrevf0sdMock - mean(robPrevf0sdMock, na.rm=TRUE),
         mockf0CV = robPrevf0sdMock / robPrevf0meanMock,
         mockf0CVc = mockf0CV - mean(mockf0CV, na.rm=TRUE),
         f0sdZ = (f0sd - mean(f0sd, na.rm=TRUE))/sd(f0sd, na.rm=TRUE),
         robf0sdZ = robf0sdc / sd(robPrevf0sd, na.rm=TRUE),
         f0CVz = (f0CV - mean(f0CV, na.rm=TRUE))/sd(f0CV, na.rm=TRUE),
         robf0CVz = robf0CVc / sd(robf0CV, na.rm=TRUE),
         f0meanZ = (f0mean - mean(f0mean, na.rm=TRUE))/sd(f0mean, na.rm=TRUE),
         robf0meanZ = robf0meanc / sd(robPrevf0mean, na.rm = TRUE),
         f0meanc = (f0mean - mean(f0mean, na.rm=TRUE)/sd(f0mean, na.rm=TRUE)),
         f0sdc = (f0sd - mean(f0sd, na.rm=TRUE)/sd(f0sd, na.rm=TRUE))) %>%
  ungroup() %>% 
  mutate(ESc = EmotionalStability - mean(EmotionalStability, na.rm=TRUE),
         Agreec = Agreeableness - mean(Agreeableness, na.rm=TRUE),
         Conscc = Conscientiousness - mean(Conscientiousness, na.rm=TRUE),
         Extrac = Extraversion - mean(Extraversion, na.rm=TRUE),
         IOc = IntellectOpenness - mean(IntellectOpenness, na.rm=TRUE),
         ConvQualc = PCConvQuality - mean(PCConvQuality, na.rm=TRUE),
         EvalRobotc = PCEvalRobot - mean(PCEvalRobot, na.=TRUE),
         IPUDurC = IPUDur - mean(IPUDur, na.rm=TRUE)) #%>% 
  # filter(scoreEN > 60) # see with and without low-level participants


dab <- dab %>%
  mutate_at(c("condition"), as.factor) %>% 
  group_by(speaker) %>% 
  mutate(robf0meanc = robPrevf0mean - mean(robPrevf0mean, na.rm=TRUE),
         robf0sdc = robPrevf0sd - mean(robPrevf0sd, na.rm=TRUE),
         mockf0meanC = robPrevf0meanMock - mean(robPrevf0meanMock, na.rm=TRUE),
         mockf0sdC = robPrevf0sdMock - mean(robPrevf0sdMock, na.rm=TRUE)) %>% 
  ungroup()

theme_set(theme_minimal())


### GA data

ga <- readxl::read_excel("C:/Users/offredet/Documents/1HU/ExperimentEyes/Data/GASpeakingSplit.xlsx") |> 
  rename(speaker = partId, condition = sType, GA = totalGARatio) |> 
  select(speaker, condition, GA)

dac <- merge(dac, ga, by=c("speaker", "condition")) |> 
  mutate_at(c("GA"), as.numeric)
```

# Calculate convergence per participant per condition

```{r}
ggplot(dac, aes(robPrevf0mean, f0mean, color=condition))+
  geom_point(aes(color=condition))+
  geom_smooth(method="lm")+
  facet_wrap(~speaker)
# ggsave(paste0(folderConvPlots, "individualConvPerCondition.png"), height=2500, width=2500, units = "px")

ggplot(dac, aes(robPrevf0mean, f0mean))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(speaker~round(GA,3))
# ggsave(paste0(folderConvPlots, "individualConvPerGA.png"), height=2500, width=2500, units = "px")


speakers <- unique(dac$speaker[!grepl("Robot", dac$speaker)])

syn <- data.frame(matrix(nrow=0, ncol=6))
names(syn) <- c("speaker", "condition", "feature", "estimate", "t", "p")

for(s in speakers){
  # f0 mean
  c <- tidy(lm(f0mean ~ robf0meanc, dac |> filter(speaker==s)))
  syn[nrow(syn)+1,] <- c(s, "overall", "f0mean", c$estimate[2], c$statistic[2], c$p.value[2])
  
  c <- tidy(lm(f0mean ~ robf0meanc, dac |> filter(speaker==s, condition=="GA")))
  syn[nrow(syn)+1,] <- c(s, "GA", "f0mean", c$estimate[2], c$statistic[2], c$p.value[2])
  
  c <- tidy(lm(f0mean ~ robf0meanc, dac |> filter(speaker==s, condition=="NG")))
  syn[nrow(syn)+1,] <- c(s, "FG", "f0mean", c$estimate[2], c$statistic[2], c$p.value[2])
  
  # f0 SD
  # c <- tidy(lm(f0sd ~ robf0sdc, dac |> filter(speaker==s)))
  # syn[nrow(syn)+1,] <- c(s, "overall", "f0sd", c$estimate[2], c$statistic[2], c$p.value[2])
  # 
  # c <- tidy(lm(f0sd ~ robf0sdc, dac |> filter(speaker==s, condition=="GA")))
  # syn[nrow(syn)+1,] <- c(s, "GA", "f0sd", c$estimate[2], c$statistic[2], c$p.value[2])
  # 
  # c <- tidy(lm(f0sd ~ robf0sdc, dac |> filter(speaker==s, condition=="NG")))
  # syn[nrow(syn)+1,] <- c(s, "FG", "f0sd", c$estimate[2], c$statistic[2], c$p.value[2])
}

syn <- syn |> 
  mutate_at(c("estimate", "t", "p"), as.numeric) |> 
  mutate(direction = ifelse(estimate < 0, "divergence", "convergence"),
         significant = ifelse(p < 0.05, "*", "ns"),
         significantCorrected = ifelse(p < (0.05 / nrow(syn)), "*", "ns"))

###
sp <- c("MOJ", "NLF", "UXE")

ggplot(dac |> filter(speaker=="MOJ"), aes(robPrevf0mean, f0mean))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~round(GA,3))
summary(m1 <- lm(f0mean ~ robf0meanc, dac |> filter(speaker=="MOJ")))
summary(m2 <- lm(f0mean ~ robf0meanc + robf0meanc : GA, dac |> filter(speaker=="MOJ")))
AIC(m1, m2)

ggplot(dac |> filter(speaker=="NLF"), aes(robPrevf0mean, f0mean))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~round(GA,3))
summary(m1 <- lm(f0mean ~ robf0meanc, dac |> filter(speaker=="NLF")))
summary(m2 <- lm(f0mean ~ robf0meanc + robf0meanc : GA, dac |> filter(speaker=="NLF")))
AIC(m1, m2)

ggplot(dac |> filter(speaker=="UXE"), aes(robPrevf0mean, f0mean))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~round(GA,3))
summary(m1 <- lm(f0mean ~ robf0meanc, dac |> filter(speaker=="UXE")))
summary(m2 <- lm(f0mean ~ robf0meanc + robf0meanc : GA, dac |> filter(speaker=="UXE")))
AIC(m1, m2)


#####################################

summary(lmer(f0mean ~ robf0meanc + robf0meanc : GA + (1|speaker), dac))

m1 <- (lmer(f0mean ~ robf0meanc + (1|speaker), dac))
summary(m2 <- (lmer(f0mean ~ robf0meanc + robf0meanc : GA + (1|speaker), dac)))
summary(m1 <- (lmer(f0mean ~ robf0meanc : GA + (1|speaker), dac)))
anova(m1, m2)
```

