---
title: "Participants"
output: html_document
date: '2022-07-05'
---

```{r, include=FALSE}
library(tidyverse)
folder <- "C:/Users/offredet/Documents/1HU/ExperimentEyes/Data/"
meta <- list.files(folder, "metadata")

dat <- read.csv(paste0(folder, meta), sep=";") %>%
  select("Participant", "Age", "Gender", "HearingImpairment", "SpeechImpairment", "Dyslexia", "VisionImpairment", "Education", "L1", "TMF.M1":"TMF.F6", "scoreEN") %>%
  mutate(TMF.M = (TMF.M1 + TMF.M2 + TMF.M3 + TMF.M4 + TMF.M5 + TMF.M6) / 6,
         TMF.F = (TMF.F1 + TMF.F2 + TMF.F3 + TMF.F4 + TMF.F5 + TMF.F6) / 6) %>%
  mutate_at(c("TMF.M", "TMF.F"), as.numeric) %>%
  select(-c("TMF.M1":"TMF.F6"))
```


```{r}
head(dat)
```

```{r}
length(dat$Participant) # 33 participants
summary(dat$Age) # 21 - 56 yo ; median 29 ; M 30.55 ; SD 8.07
sd(dat$Age)
table(dat$Education) # 5 HS ; 6 BA ; 22 MA
```

```{r}
table(dat$Gender) # 32 males; 1 not listed

summary(dat$TMF.F) # 1.17 - 5 ; median 3.33 ; M 3.16 ; SD 0.88
sd(dat$TMF.F, na.rm=TRUE)
summary(dat$TMF.M) # 3.33 - 7 ; median 5.33 ; M 5.34 ; SD 0.9
sd(dat$TMF.M)
```

```{r}
# first make sure that each row counts one language, so we get a notion of how many native speakers each language has (independently of whether a given speaker also has other L1s)

langs <- data.frame(table(dat$L1))
names(langs) <- c("language", "count")
langs$language <- as.character(langs$language)
tempL <- data.frame(matrix(nrow=0, ncol=3))
names(tempL) <- c("language", "count", "rowN")
for(i in 1:nrow(langs)){
  if(grepl("_", langs$language[i])){
    l1 <- strsplit(as.character(langs$language[i]), split="_")[[1]][[1]]
    l2 <- strsplit(as.character(langs$language[i]), split="_")[[1]][[2]]
    c <- langs$count[i]
    tempL[nrow(tempL)+1,] <- c(l1, c, i)
    tempL[nrow(tempL)+1,] <- c(l2, c, i)
  }
}
langs <- langs %>% slice(-c(unique(as.integer(tempL$rowN))))
for(i in 1:nrow(tempL)){
  if(any(grepl(tempL$language[i], unique(langs$language)))){
    langs$count[langs$language==tempL$language[i]] <- as.integer(langs$count[langs$language==tempL$language[i]]) + as.integer(tempL$count[i])
  } else{
    langs[nrow(langs)+1,] <- c(tempL$language[i], tempL$count[i])
  }
}
langs$language <- as.factor(langs$language)
remove(tempL)

arrange(langs, desc(count))
length(unique(langs$language)) # 17 different languages
```


```{r}
table(dat$HearingImpairment) # no hearing impairment
table(dat$SpeechImpairment) # no speech impairment
table(dat$Dyslexia) # 1 dyslexic
table(dat$VisionImpairment) # 28 no vision impairment, 5 corrected-to-normal vision
```

```{r}
summary(dat$scoreEN)
hist(dat$scoreEN)
dat <- dat %>% 
  mutate(levelEN = ifelse(scoreEN >= 80, "C1-C2", ifelse(scoreEN < 80 & scoreEN > 60, "B2", "B1<")))
table(dat$levelEN)
```